spring.application.name=finpilot-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/finpilot
spring.datasource.username=anshdesai
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=0
spring.flyway.clean-disabled=false

firebase.credentials=/Users/anshdesai/Documents/Mustang/finpilot-15-firebase-adminsdk-fbsvc-51e02692e9.json

app.auth.allow-demo=false

app.plaid.env=${APP_PLAID_ENV:sandbox}
app.plaid.client-id=${APP_PLAID_CLIENT_ID}
app.plaid.secret=${APP_PLAID_SECRET}